openapi: 3.1.0
info:
  title: Basescan Accounts API PRO Endpoints API
  version: 1.0.0
  description: Basescan is the leading blockchain explorer, search, API and analytics platform for Base (L2), an Ethereum Layer 2 network. Powered by the Etherscan team and compatible with the unified Etherscan API V2 platform using chain ID 8453 for Base network access.
  license:
    name: UNLICENSED
    url: https://docs.basescan.org/
servers:
- url: https://api.basescan.org/api
  description: Base Mainnet Endpoint
- url: https://api-sepolia.basescan.org/api
  description: Base Sepolia Testnet Endpoint
security:
- apiKeyAuth: []
tags:
- name: API PRO Endpoints
paths:
  /?module=account&action=balancehistory:
    get:
      operationId: get-historical-ether-balance-for-a-single-address-by-blockno
      externalDocs:
        url: https://docs.etherscan.io/api-endpoints/accounts#get-historical-ether-balance-for-a-single-address-by-blockno
      summary: Get Historical Ether Balance for a Single Address By BlockNo
      description: 'Returns the balance of an address at a certain block height. 📝 Note : This endpoint is throttled to 2 calls/second regardless of API Pro tier. PRO endpoint.'
      tags:
      - API PRO Endpoints
      parameters:
      - in: query
        name: address
        schema:
          $ref: '#/components/schemas/AddressHash'
        required: true
        example: '0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae'
      - in: query
        name: blockno
        schema:
          $ref: '#/components/schemas/IntegerMin0'
        required: true
        example: '8000000'
      responses:
        '200':
          description: 'Operation result. 📖 Tip: The result field is denoted in wei.'
          content:
            application/json:
              schema:
                oneOf:
                - allOf:
                  - $ref: '#/components/schemas/ResponseOK'
                  - $ref: '#/components/schemas/Result.account.balancehistory'
                - $ref: '#/components/schemas/ResponseNOTOK'
              example:
                status: '1'
                message: OK
                result: '610538078574759898951277'
  /?module=stats&action=dailyavgblocksize:
    get:
      operationId: get-daily-average-block-size
      externalDocs:
        url: https://docs.etherscan.io/api-endpoints/blocks#get-daily-average-block-size
      summary: Get Daily Average Block Size
      description: Returns the daily average block size within a date range. PRO endpoint.
      tags:
      - API PRO Endpoints
      parameters:
      - in: query
        name: startdate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-01'
      - in: query
        name: enddate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-28'
      - in: query
        name: sort
        schema:
          $ref: '#/components/schemas/PageSort'
        required: false
        example: asc
      responses:
        '200':
          description: Operation result.
          content:
            application/json:
              schema:
                oneOf:
                - allOf:
                  - $ref: '#/components/schemas/ResponseOK'
                  - $ref: '#/components/schemas/Result.stats.dailyavgblocksize'
                - $ref: '#/components/schemas/ResponseNOTOK'
              example:
                status: '1'
                message: OK
                result:
                - UTCDate: '2019-02-01'
                  unixTimeStamp: '1548979200'
                  blockSize_bytes: 20373
                - UTCDate: '2019-02-28'
                  unixTimeStamp: '1551312000'
                  blockSize_bytes: 25117
  /?module=stats&action=dailyblkcount:
    get:
      operationId: get-daily-block-count-and-rewards
      externalDocs:
        url: https://docs.etherscan.io/api-endpoints/blocks#get-daily-block-count-and-rewards
      summary: Get Daily Block Count and Rewards
      description: Returns the number of blocks mined daily and the amount of block rewards. PRO endpoint.
      tags:
      - API PRO Endpoints
      parameters:
      - in: query
        name: startdate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-01'
      - in: query
        name: enddate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-28'
      - in: query
        name: sort
        schema:
          $ref: '#/components/schemas/PageSort'
        required: false
        example: asc
      responses:
        '200':
          description: Operation result.
          content:
            application/json:
              schema:
                oneOf:
                - allOf:
                  - $ref: '#/components/schemas/ResponseOK'
                  - $ref: '#/components/schemas/Result.stats.dailyblkcount'
                - $ref: '#/components/schemas/ResponseNOTOK'
              example:
                status: '1'
                message: OK
                result:
                - UTCDate: '2019-02-01'
                  unixTimeStamp: '1548979200'
                  blockCount: 4848
                  blockRewards_Eth: '14929.464690870590355682'
                - UTCDate: '2019-02-28'
                  unixTimeStamp: '1551312000'
                  blockCount: 4366
                  blockRewards_Eth: '12808.485512162356907132'
  /?module=stats&action=dailyblockrewards:
    get:
      operationId: get-daily-block-rewards
      externalDocs:
        url: https://docs.etherscan.io/api-endpoints/blocks#get-daily-block-rewards
      summary: Get Daily Block Rewards
      description: Returns the amount of block rewards distributed to miners daily. PRO endpoint.
      tags:
      - API PRO Endpoints
      parameters:
      - in: query
        name: startdate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-01'
      - in: query
        name: enddate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-28'
      - in: query
        name: sort
        schema:
          $ref: '#/components/schemas/PageSort'
        required: false
        example: asc
      responses:
        '200':
          description: Operation result.
          content:
            application/json:
              schema:
                oneOf:
                - allOf:
                  - $ref: '#/components/schemas/ResponseOK'
                  - $ref: '#/components/schemas/Result.stats.dailyblockrewards'
                - $ref: '#/components/schemas/ResponseNOTOK'
              example:
                status: '1'
                message: OK
                result:
                - UTCDate: '2019-02-01'
                  unixTimeStamp: '1548979200'
                  blockRewards_Eth: '15300.65625'
                - UTCDate: '2019-02-28'
                  unixTimeStamp: '1551312000'
                  blockRewards_Eth: '12954.84375'
  /?module=stats&action=dailyavgblocktime:
    get:
      operationId: get-daily-average-time-for-a-block-to-be-included-in-the-ethereum-blockchain
      externalDocs:
        url: https://docs.etherscan.io/api-endpoints/blocks#get-daily-average-time-for-a-block-to-be-included-in-the-ethereum-blockchain
      summary: Get Daily Average Time for A Block to be Included in the Ethereum Blockchain
      description: Returns the daily average of time needed for a block to be successfully mined. PRO endpoint.
      tags:
      - API PRO Endpoints
      parameters:
      - in: query
        name: startdate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-01'
      - in: query
        name: enddate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-28'
      - in: query
        name: sort
        schema:
          $ref: '#/components/schemas/PageSort'
        required: false
        example: asc
      responses:
        '200':
          description: Operation result.
          content:
            application/json:
              schema:
                oneOf:
                - allOf:
                  - $ref: '#/components/schemas/ResponseOK'
                  - $ref: '#/components/schemas/Result.stats.dailyavgblocktime'
                - $ref: '#/components/schemas/ResponseNOTOK'
              example:
                status: '1'
                message: OK
                result:
                - UTCDate: '2019-02-01'
                  unixTimeStamp: '1548979200'
                  blockTime_sec: '17.67'
                - UTCDate: '2019-02-28'
                  unixTimeStamp: '1551312000'
                  blockTime_sec: '19.61'
  /?module=stats&action=dailyuncleblkcount:
    get:
      operationId: get-daily-uncle-block-count-and-rewards
      externalDocs:
        url: https://docs.etherscan.io/api-endpoints/blocks#get-daily-uncle-block-count-and-rewards
      summary: Get Daily Uncle Block Count and Rewards
      description: Returns the number of 'Uncle' blocks mined daily and the amount of 'Uncle' block rewards. PRO endpoint.
      tags:
      - API PRO Endpoints
      parameters:
      - in: query
        name: startdate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-01'
      - in: query
        name: enddate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-28'
      - in: query
        name: sort
        schema:
          $ref: '#/components/schemas/PageSort'
        required: false
        example: asc
      responses:
        '200':
          description: Operation result.
          content:
            application/json:
              schema:
                oneOf:
                - allOf:
                  - $ref: '#/components/schemas/ResponseOK'
                  - $ref: '#/components/schemas/Result.stats.dailyuncleblkcount'
                - $ref: '#/components/schemas/ResponseNOTOK'
              example:
                status: '1'
                message: OK
                result:
                - UTCDate: '2019-02-01'
                  unixTimeStamp: '1548979200'
                  uncleBlockCount: 287
                  uncleBlockRewards_Eth: '729.75'
                - UTCDate: '2019-02-28'
                  unixTimeStamp: '1551312000'
                  uncleBlockCount: 288
                  uncleBlockRewards_Eth: '691.5'
  /?module=stats&action=tokensupplyhistory:
    get:
      operationId: get-historical-erc20-token-totalsupply-by-contractaddress-and-blockno
      externalDocs:
        url: https://docs.etherscan.io/api-endpoints/tokens#get-historical-erc20-token-totalsupply-by-contractaddress-and-blockno
      summary: Get Historical ERC20-Token TotalSupply by ContractAddress & BlockNo
      description: 'Returns the amount of an ERC-20 token in circulation at a certain block height. 📝 Note : This endpoint is throttled to 2 calls/second regardless of API Pro tier. PRO endpoint.'
      tags:
      - API PRO Endpoints
      parameters:
      - in: query
        name: contractaddress
        schema:
          $ref: '#/components/schemas/AddressHash'
        required: true
        example: '0x57d90b64a1a57749b0f932f1a3395792e12e7055'
      - in: query
        name: blockno
        schema:
          $ref: '#/components/schemas/IntegerMin0'
        required: true
        example: '8000000'
      responses:
        '200':
          description: 'Operation result. 📈 Tip : The result is returned in the token''s smallest decimal representation.Eg. a token with a balance of 215.241526476136819398 and 18 decimal places will be returned as 215241526476136819398'
          content:
            application/json:
              schema:
                oneOf:
                - allOf:
                  - $ref: '#/components/schemas/ResponseOK'
                  - $ref: '#/components/schemas/Result.stats.tokensupplyhistory'
                - $ref: '#/components/schemas/ResponseNOTOK'
              example:
                status: '1'
                message: OK
                result: '21265524714464'
  /?module=account&action=tokenbalancehistory:
    get:
      operationId: get-historical-erc20-token-account-balance-for-tokencontractaddress-by-blockno
      externalDocs:
        url: https://docs.etherscan.io/api-endpoints/tokens#get-historical-erc20-token-account-balance-for-tokencontractaddress-by-blockno
      summary: Get Historical ERC20-Token Account Balance for TokenContractAddress by BlockNo
      description: 'Returns the balance of an ERC-20 token of an address at a certain block height. 📝 Note : This endpoint is throttled to 2 calls/second regardless of API Pro tier. PRO endpoint.'
      tags:
      - API PRO Endpoints
      parameters:
      - in: query
        name: contractaddress
        schema:
          $ref: '#/components/schemas/AddressHash'
        required: true
        example: '0x57d90b64a1a57749b0f932f1a3395792e12e7055'
      - in: query
        name: address
        schema:
          $ref: '#/components/schemas/AddressHash'
        required: true
        example: '0xe04f27eb70e025b78871a2ad7eabe85e61212761'
      - in: query
        name: blockno
        schema:
          $ref: '#/components/schemas/IntegerMin0'
        required: true
        example: '8000000'
      responses:
        '200':
          description: 'Operation result. 📈 Tip : The result is returned in the token''s smallest decimal representation.Eg. a token with a balance of 215.241526476136819398 and 18 decimal places will be returned as 215241526476136819398'
          content:
            application/json:
              schema:
                oneOf:
                - allOf:
                  - $ref: '#/components/schemas/ResponseOK'
                  - $ref: '#/components/schemas/Result.account.tokenbalancehistory'
                - $ref: '#/components/schemas/ResponseNOTOK'
              example:
                status: '1'
                message: OK
                result: '135499'
  /?module=token&action=tokeninfo:
    get:
      operationId: get-token-info-by-contractaddress
      externalDocs:
        url: https://docs.etherscan.io/api-endpoints/tokens#get-token-info-by-contractaddress
      summary: Get Token Info by ContractAddress
      description: 'Returns project information and social media links of an ERC20/ERC721/ERC1155 token. 📝 Note : This endpoint is throttled to 2 calls/second regardless of API Pro tier. PRO endpoint.'
      tags:
      - API PRO Endpoints
      parameters:
      - in: query
        name: contractaddress
        schema:
          $ref: '#/components/schemas/AddressHash'
        required: true
        example: '0x0e3a2a1f2146d86a604adc220b4967a898d7fe07'
      responses:
        '200':
          description: Operation result.
          content:
            application/json:
              schema:
                oneOf:
                - allOf:
                  - $ref: '#/components/schemas/ResponseOK'
                  - $ref: '#/components/schemas/Result.token.tokeninfo'
                - $ref: '#/components/schemas/ResponseNOTOK'
              example:
                status: '1'
                message: OK
                result:
                - contractAddress: '0x0e3a2a1f2146d86a604adc220b4967a898d7fe07'
                  tokenName: Gods Unchained Cards
                  symbol: CARD
                  divisor: '0'
                  tokenType: ERC721
                  totalSupply: '6962498'
                  blueCheckmark: 'true'
                  description: A TCG on the Ethereum blockchain that uses NFT's to bring real ownership to in-game assets.
                  website: https://godsunchained.com/
                  email: ''
                  blog: https://medium.com/@fuelgames
                  reddit: https://www.reddit.com/r/GodsUnchained/
                  slack: ''
                  facebook: https://www.facebook.com/godsunchained/
                  twitter: https://twitter.com/godsunchained
                  bitcointalk: ''
                  github: ''
                  telegram: ''
                  wechat: ''
                  linkedin: ''
                  discord: https://discordapp.com/invite/DKGr2pW
                  whitepaper: ''
                  tokenPriceUSD: '0.000000000000000000'
  /?module=stats&action=dailyavggaslimit:
    get:
      operationId: get-daily-average-gas-limit
      externalDocs:
        url: https://docs.etherscan.io/api-endpoints/gas-tracker#get-daily-average-gas-limit
      summary: Get Daily Average Gas Limit
      description: Returns the historical daily average gas limit of the Ethereum network. PRO endpoint.
      tags:
      - API PRO Endpoints
      parameters:
      - in: query
        name: startdate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-01'
      - in: query
        name: enddate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-28'
      - in: query
        name: sort
        schema:
          $ref: '#/components/schemas/PageSort'
        required: false
        example: asc
      responses:
        '200':
          description: Operation result.
          content:
            application/json:
              schema:
                oneOf:
                - allOf:
                  - $ref: '#/components/schemas/ResponseOK'
                  - $ref: '#/components/schemas/Result.stats.dailyavggaslimit'
                - $ref: '#/components/schemas/ResponseNOTOK'
              example:
                status: '1'
                message: OK
                result:
                - UTCDate: '2019-02-01'
                  unixTimeStamp: '1548979200'
                  gasLimit: '8001360'
                - UTCDate: '2019-02-27'
                  unixTimeStamp: '1551225600'
                  gasLimit: '8001071'
                - UTCDate: '2019-02-28'
                  unixTimeStamp: '1551312000'
                  gasLimit: '8001137'
  /?module=stats&action=dailygasused:
    get:
      operationId: get-ethereum-daily-total-gas-used
      externalDocs:
        url: https://docs.etherscan.io/api-endpoints/gas-tracker#get-ethereum-daily-total-gas-used
      summary: Get Ethereum Daily Total Gas Used
      description: Returns the total amount of gas used daily for transctions on the Ethereum network. PRO endpoint.
      tags:
      - API PRO Endpoints
      parameters:
      - in: query
        name: startdate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-01'
      - in: query
        name: enddate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-28'
      - in: query
        name: sort
        schema:
          $ref: '#/components/schemas/PageSort'
        required: false
        example: asc
      responses:
        '200':
          description: Operation result.
          content:
            application/json:
              schema:
                oneOf:
                - allOf:
                  - $ref: '#/components/schemas/ResponseOK'
                  - $ref: '#/components/schemas/Result.stats.dailygasused'
                - $ref: '#/components/schemas/ResponseNOTOK'
              example:
                status: '1'
                message: OK
                result:
                - UTCDate: '2019-02-01'
                  unixTimeStamp: '1548979200'
                  gasUsed: '32761450415'
                - UTCDate: '2019-02-27'
                  unixTimeStamp: '1551225600'
                  gasUsed: '32657440136'
                - UTCDate: '2019-02-28'
                  unixTimeStamp: '1551312000'
                  gasUsed: '33081119561'
  /?module=stats&action=dailyavggasprice:
    get:
      operationId: get-daily-average-gas-price
      externalDocs:
        url: https://docs.etherscan.io/api-endpoints/gas-tracker#get-daily-average-gas-price
      summary: Get Daily Average Gas Price
      description: Returns the daily average gas price used on the Ethereum network. PRO endpoint.
      tags:
      - API PRO Endpoints
      parameters:
      - in: query
        name: startdate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-01'
      - in: query
        name: enddate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-28'
      - in: query
        name: sort
        schema:
          $ref: '#/components/schemas/PageSort'
        required: false
        example: asc
      responses:
        '200':
          description: Operation result.
          content:
            application/json:
              schema:
                oneOf:
                - allOf:
                  - $ref: '#/components/schemas/ResponseOK'
                  - $ref: '#/components/schemas/Result.stats.dailyavggasprice'
                - $ref: '#/components/schemas/ResponseNOTOK'
              example:
                status: '1'
                message: OK
                result:
                - UTCDate: '2019-02-01'
                  unixTimeStamp: '1548979200'
                  maxGasPrice_Wei: '60814303896257'
                  minGasPrice_Wei: '432495'
                  avgGasPrice_Wei: '13234562600'
                - UTCDate: '2019-02-27'
                  unixTimeStamp: '1551225600'
                  maxGasPrice_Wei: '42000000000000'
                  minGasPrice_Wei: '1000000'
                  avgGasPrice_Wei: '16334617513'
                - UTCDate: '2019-02-28'
                  unixTimeStamp: '1551312000'
                  maxGasPrice_Wei: '237222222222257'
                  minGasPrice_Wei: '100000000'
                  avgGasPrice_Wei: '18834674068'
  /?module=stats&action=dailytxnfee:
    get:
      operationId: get-daily-network-transaction-fee
      externalDocs:
        url: https://docs.etherscan.io/api-endpoints/stats-1#get-daily-network-transaction-fee
      summary: Get Daily Network Transaction Fee
      description: Returns the amount of transaction fees paid to miners per day. PRO endpoint.
      tags:
      - API PRO Endpoints
      parameters: []
      responses:
        '200':
          description: Operation result.
          content:
            application/json:
              schema:
                oneOf:
                - allOf:
                  - $ref: '#/components/schemas/ResponseOK'
                  - $ref: '#/components/schemas/Result.stats.dailytxnfee'
                - $ref: '#/components/schemas/ResponseNOTOK'
              example:
                status: '1'
                message: OK
                result:
                - UTCDate: '2019-02-01'
                  unixTimeStamp: '1548979200'
                  transactionFee_Eth: '358.558440870590355682'
                - UTCDate: '2019-02-28'
                  unixTimeStamp: '1551312000'
                  transactionFee_Eth: '545.141762162356907132'
  /?module=stats&action=dailynewaddress:
    get:
      operationId: get-daily-new-address-count
      externalDocs:
        url: https://docs.etherscan.io/api-endpoints/stats-1#get-daily-new-address-count
      summary: Get Daily New Address Count
      description: Returns the number of new Ethereum addresses created per day. PRO endpoint.
      tags:
      - API PRO Endpoints
      parameters:
      - in: query
        name: startdate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-01'
      - in: query
        name: enddate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-28'
      - in: query
        name: sort
        schema:
          $ref: '#/components/schemas/PageSort'
        required: false
        example: asc
      responses:
        '200':
          description: Operation result.
          content:
            application/json:
              schema:
                oneOf:
                - allOf:
                  - $ref: '#/components/schemas/ResponseOK'
                  - $ref: '#/components/schemas/Result.stats.dailynewaddress'
                - $ref: '#/components/schemas/ResponseNOTOK'
              example:
                status: '1'
                message: OK
                result:
                - UTCDate: '2019-02-01'
                  unixTimeStamp: '1548979200'
                  newAddressCount: 54081
                - UTCDate: '2019-02-28'
                  unixTimeStamp: '1551312000'
                  newAddressCount: 53117
  /?module=stats&action=dailynetutilization:
    get:
      operationId: get-daily-network-utilization
      externalDocs:
        url: https://docs.etherscan.io/api-endpoints/stats-1#get-daily-network-utilization
      summary: Get Daily Network Utilization
      description: Returns the daily average gas used over gas limit, in percentage. PRO endpoint.
      tags:
      - API PRO Endpoints
      parameters:
      - in: query
        name: startdate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-01'
      - in: query
        name: enddate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-28'
      - in: query
        name: sort
        schema:
          $ref: '#/components/schemas/PageSort'
        required: false
        example: asc
      responses:
        '200':
          description: Operation result.
          content:
            application/json:
              schema:
                oneOf:
                - allOf:
                  - $ref: '#/components/schemas/ResponseOK'
                  - $ref: '#/components/schemas/Result.stats.dailynetutilization'
                - $ref: '#/components/schemas/ResponseNOTOK'
              example:
                status: '1'
                message: OK
                result:
                - UTCDate: '2019-02-01'
                  unixTimeStamp: '1548979200'
                  networkUtilization: '0.8464'
                - UTCDate: '2019-02-28'
                  unixTimeStamp: '1551312000'
                  networkUtilization: '0.9472'
  /?module=stats&action=dailyavghashrate:
    get:
      operationId: get-daily-average-network-hash-rate
      externalDocs:
        url: https://docs.etherscan.io/api-endpoints/stats-1#get-daily-average-network-hash-rate
      summary: Get Daily Average Network Hash Rate
      description: Returns the historical measure of processing power of the Ethereum network. PRO endpoint.
      tags:
      - API PRO Endpoints
      parameters:
      - in: query
        name: startdate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-01'
      - in: query
        name: enddate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-28'
      - in: query
        name: sort
        schema:
          $ref: '#/components/schemas/PageSort'
        required: false
        example: asc
      responses:
        '200':
          description: 'Operation result. 🔥 Tip : The networkHashRate is represented in GigaHashes ( GH/s ).'
          content:
            application/json:
              schema:
                oneOf:
                - allOf:
                  - $ref: '#/components/schemas/ResponseOK'
                  - $ref: '#/components/schemas/Result.stats.dailyavghashrate'
                - $ref: '#/components/schemas/ResponseNOTOK'
              example:
                status: '1'
                message: OK
                result:
                - UTCDate: '2019-02-01'
                  unixTimeStamp: '1548979200'
                  networkHashRate: '143116.0140'
                - UTCDate: '2019-02-28'
                  unixTimeStamp: '1551312000'
                  networkHashRate: '157689.3983'
  /?module=stats&action=dailytx:
    get:
      operationId: get-daily-transaction-count
      externalDocs:
        url: https://docs.etherscan.io/api-endpoints/stats-1#get-daily-transaction-count
      summary: Get Daily Transaction Count
      description: Returns the number of transactions performed on the Ethereum blockchain per day. PRO endpoint.
      tags:
      - API PRO Endpoints
      parameters:
      - in: query
        name: startdate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-01'
      - in: query
        name: enddate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-28'
      - in: query
        name: sort
        schema:
          $ref: '#/components/schemas/PageSort'
        required: false
        example: asc
      responses:
        '200':
          description: Operation result.
          content:
            application/json:
              schema:
                oneOf:
                - allOf:
                  - $ref: '#/components/schemas/ResponseOK'
                  - $ref: '#/components/schemas/Result.stats.dailytx'
                - $ref: '#/components/schemas/ResponseNOTOK'
              example:
                status: '1'
                message: OK
                result:
                - UTCDate: '2019-02-01'
                  unixTimeStamp: '1548979200'
                  transactionCount: 498856
                - UTCDate: '2019-02-28'
                  unixTimeStamp: '1551312000'
                  transactionCount: 541458
  /?module=stats&action=dailyavgnetdifficulty:
    get:
      operationId: get-daily-average-network-difficulty
      externalDocs:
        url: https://docs.etherscan.io/api-endpoints/stats-1#get-daily-average-network-difficulty
      summary: Get Daily Average Network Difficulty
      description: Returns the historical mining difficulty of the Ethereum network. PRO endpoint.
      tags:
      - API PRO Endpoints
      parameters:
      - in: query
        name: startdate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-01'
      - in: query
        name: enddate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-28'
      - in: query
        name: sort
        schema:
          $ref: '#/components/schemas/PageSort'
        required: false
        example: asc
      responses:
        '200':
          description: 'Operation result. ​​ 🔥 Tip : The networkDifficulty is represented in TeraHashes ( TH/s ).'
          content:
            application/json:
              schema:
                oneOf:
                - allOf:
                  - $ref: '#/components/schemas/ResponseOK'
                  - $ref: '#/components/schemas/Result.stats.dailyavgnetdifficulty'
                - $ref: '#/components/schemas/ResponseNOTOK'
              example:
                status: '1'
                message: OK
                result:
                - UTCDate: '2019-02-01'
                  unixTimeStamp: '1548979200'
                  networkDifficulty: 2,408.028
                - UTCDate: '2019-02-28'
                  unixTimeStamp: '1551312000'
                  networkDifficulty: 2,927.453
  /?module=stats&action=ethdailymarketcap:
    get:
      operationId: get-ether-historical-daily-market-cap
      externalDocs:
        url: https://docs.etherscan.io/api-endpoints/stats-1#get-ether-historical-daily-market-cap
      summary: Get Ether Historical Daily Market Cap
      description: Returns the historical Ether daily market capitalization. PRO endpoint.
      tags:
      - API PRO Endpoints
      parameters:
      - in: query
        name: startdate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-01'
      - in: query
        name: enddate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-28'
      - in: query
        name: sort
        schema:
          $ref: '#/components/schemas/PageSort'
        required: false
        example: asc
      responses:
        '200':
          description: 'Operation result. ​​ 💰 Tip : The marketCap is represented in million US Dollars ( USD ).'
          content:
            application/json:
              schema:
                oneOf:
                - allOf:
                  - $ref: '#/components/schemas/ResponseOK'
                  - $ref: '#/components/schemas/Result.stats.ethdailymarketcap'
                - $ref: '#/components/schemas/ResponseNOTOK'
              example:
                status: '1'
                message: OK
                result:
                - UTCDate: '2019-02-01'
                  unixTimeStamp: '1548979200'
                  supply: '104672819.281250'
                  marketCap: '11203.1318476721875'
                  price: '107.03'
                - UTCDate: '2019-02-28'
                  unixTimeStamp: '1551312000'
                  supply: '105048576.406250'
                  marketCap: '14317.0704784078125'
                  price: '136.29'
  /?module=stats&action=ethdailyprice:
    get:
      operationId: get-ether-historical-price
      externalDocs:
        url: https://docs.etherscan.io/api-endpoints/stats-1#get-ether-historical-price
      summary: Get Ether Historical Price
      description: Returns the historical price of 1 ETH. PRO endpoint.
      tags:
      - API PRO Endpoints
      parameters:
      - in: query
        name: startdate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-01'
      - in: query
        name: enddate
        schema:
          $ref: '#/components/schemas/DateYYYYMMDD'
        required: true
        example: '2019-02-28'
      - in: query
        name: sort
        schema:
          $ref: '#/components/schemas/PageSort'
        required: false
        example: asc
      responses:
        '200':
          description: 'Operation result. ​​ 💰 Tip : The value is represented in US Dollars ( USD ).'
          content:
            application/json:
              schema:
                oneOf:
                - allOf:
                  - $ref: '#/components/schemas/ResponseOK'
                  - $ref: '#/components/schemas/Result.stats.ethdailyprice'
                - $ref: '#/components/schemas/ResponseNOTOK'
              example:
                status: '1'
                message: OK
                result:
                - UTCDate: '2019-02-01'
                  unixTimeStamp: '1548979200'
                  value: '107.03'
                - UTCDate: '2019-02-28'
                  unixTimeStamp: '1551312000'
                  value: '136.29'
components:
  schemas:
    Result.stats.ethdailyprice:
      type: object
      properties:
        result:
          type: array
          items:
            type: object
            properties:
              UTCDate:
                $ref: '#/components/schemas/DateYYYYMMDD'
              unixTimeStamp:
                $ref: '#/components/schemas/UnixTimestampString'
              value:
                $ref: '#/components/schemas/FloatString'
    Result.stats.dailytxnfee:
      type: object
      properties:
        result:
          type: array
          items:
            type: object
            properties:
              UTCDate:
                $ref: '#/components/schemas/DateYYYYMMDD'
              unixTimeStamp:
                $ref: '#/components/schemas/UnixTimestampString'
              transactionFee_Eth:
                $ref: '#/components/schemas/FloatString'
    Result.stats.dailytx:
      type: object
      properties:
        result:
          type: array
          items:
            type: object
            properties:
              UTCDate:
                $ref: '#/components/schemas/DateYYYYMMDD'
              unixTimeStamp:
                $ref: '#/components/schemas/UnixTimestampString'
              transactionCount:
                $ref: '#/components/schemas/IntegerMin0'
    Result.stats.dailygasused:
      type: object
      properties:
        result:
          type: array
          items:
            type: object
            properties:
              UTCDate:
                $ref: '#/components/schemas/DateYYYYMMDD'
              unixTimeStamp:
                $ref: '#/components/schemas/UnixTimestampString'
              gasUsed:
                $ref: '#/components/schemas/IntegerMin0String'
    Result.stats.dailyavghashrate:
      type: object
      properties:
        result:
          type: array
          items:
            type: object
            properties:
              UTCDate:
                $ref: '#/components/schemas/DateYYYYMMDD'
              unixTimeStamp:
                $ref: '#/components/schemas/UnixTimestampString'
              networkHashRate:
                $ref: '#/components/schemas/FloatString'
    Result.stats.dailyuncleblkcount:
      type: object
      properties:
        result:
          type: array
          items:
            type: object
            properties:
              UTCDate:
                $ref: '#/components/schemas/DateYYYYMMDD'
              unixTimeStamp:
                $ref: '#/components/schemas/UnixTimestampString'
              uncleBlockCount:
                $ref: '#/components/schemas/IntegerMin0'
              uncleBlockRewards_Eth:
                $ref: '#/components/schemas/FloatString'
    PageSort:
      type: string
      enum:
      - asc
      - desc
    Result.account.tokenbalancehistory:
      type: object
      properties:
        result:
          $ref: '#/components/schemas/IntegerMin0String'
    FloatString:
      type: string
      pattern: ^\d+(\.\d+)?$
      description: A float represented as a string.
    ResponseOK:
      type: object
      properties:
        status:
          type: string
          enum:
          - '1'
        message:
          type: string
          enum:
          - OK
        result:
          description: call result
      required:
      - status
      - message
      - result
    Result.account.balancehistory:
      type: object
      properties:
        result:
          $ref: '#/components/schemas/IntegerMin0String'
    Result.stats.dailyavggaslimit:
      type: object
      properties:
        result:
          type: array
          items:
            type: object
            properties:
              UTCDate:
                $ref: '#/components/schemas/DateYYYYMMDD'
              unixTimeStamp:
                $ref: '#/components/schemas/UnixTimestampString'
              gasLimit:
                $ref: '#/components/schemas/IntegerMin0String'
    Result.stats.dailyavggasprice:
      type: object
      properties:
        result:
          type: array
          items:
            type: object
            properties:
              UTCDate:
                $ref: '#/components/schemas/DateYYYYMMDD'
              unixTimeStamp:
                $ref: '#/components/schemas/UnixTimestampString'
              maxGasPrice_Wei:
                $ref: '#/components/schemas/IntegerMin0String'
              minGasPrice_Wei:
                $ref: '#/components/schemas/IntegerMin0String'
              avgGasPrice_Wei:
                $ref: '#/components/schemas/IntegerMin0String'
    Result.stats.dailyblockrewards:
      type: object
      properties:
        result:
          type: array
          items:
            type: object
            properties:
              UTCDate:
                $ref: '#/components/schemas/DateYYYYMMDD'
              unixTimeStamp:
                $ref: '#/components/schemas/UnixTimestampString'
              blockRewards_Eth:
                $ref: '#/components/schemas/FloatString'
    Result.stats.dailyblkcount:
      type: object
      properties:
        result:
          type: array
          items:
            type: object
            properties:
              UTCDate:
                $ref: '#/components/schemas/DateYYYYMMDD'
              unixTimeStamp:
                $ref: '#/components/schemas/UnixTimestampString'
              blockCount:
                $ref: '#/components/schemas/IntegerMin0'
              blockRewards_Eth:
                $ref: '#/components/schemas/FloatString'
    UnixTimestampString:
      type: string
      description: A Unix timestamp representing the number of seconds since January 1, 1970, expressed as a string.
      pattern: ^[0-9]+$
      example: '1623338323'
    Result.stats.dailynetutilization:
      type: object
      properties:
        result:
          type: array
          items:
            type: object
            properties:
              UTCDate:
                $ref: '#/components/schemas/DateYYYYMMDD'
              unixTimeStamp:
                $ref: '#/components/schemas/UnixTimestampString'
              networkUtilization:
                $ref: '#/components/schemas/FloatString'
    Result.stats.tokensupplyhistory:
      type: object
      properties:
        result:
          $ref: '#/components/schemas/IntegerMin0String'
    AddressHash:
      type: string
      pattern: 0x[A-Fa-f0-9]{40}
      example: '0x01234567890abcdef01234567890abcdef012345'
    Result.stats.dailyavgblocktime:
      type: object
      properties:
        result:
          type: array
          items:
            type: object
            properties:
              UTCDate:
                $ref: '#/components/schemas/DateYYYYMMDD'
              unixTimeStamp:
                $ref: '#/components/schemas/UnixTimestampString'
              blockTime_sec:
                $ref: '#/components/schemas/FloatString'
    IntegerMin0String:
      type: string
      pattern: '[0-9]+'
      description: An integer greater than 0 represented as a string.
    Result.stats.dailynewaddress:
      type: object
      properties:
        result:
          type: array
          items:
            type: object
            properties:
              UTCDate:
                $ref: '#/components/schemas/DateYYYYMMDD'
              unixTimeStamp:
                $ref: '#/components/schemas/UnixTimestampString'
              newAddressCount:
                $ref: '#/components/schemas/IntegerMin0'
    Result.stats.dailyavgblocksize:
      type: object
      properties:
        result:
          type: array
          items:
            type: object
            properties:
              UTCDate:
                $ref: '#/components/schemas/DateYYYYMMDD'
              unixTimeStamp:
                $ref: '#/components/schemas/UnixTimestampString'
              blockSize_bytes:
                $ref: '#/components/schemas/IntegerMin0'
    Result.stats.ethdailymarketcap:
      type: object
      properties:
        result:
          type: array
          items:
            type: object
            properties:
              UTCDate:
                $ref: '#/components/schemas/DateYYYYMMDD'
              unixTimeStamp:
                $ref: '#/components/schemas/UnixTimestampString'
              supply:
                $ref: '#/components/schemas/FloatString'
              marketCap:
                $ref: '#/components/schemas/FloatString'
              price:
                $ref: '#/components/schemas/FloatString'
    IntegerMin0:
      type: integer
      minimum: 0
    Result.token.tokeninfo:
      type: object
      properties:
        result:
          type: array
          items:
            type: object
            additionalProperties: true
          maxItems: 1
    Result.stats.dailyavgnetdifficulty:
      type: object
      properties:
        result:
          type: array
          items:
            type: object
            properties:
              UTCDate:
                $ref: '#/components/schemas/DateYYYYMMDD'
              unixTimeStamp:
                $ref: '#/components/schemas/UnixTimestampString'
              networkDifficulty:
                $ref: '#/components/schemas/FloatWithCommasString'
    DateYYYYMMDD:
      type: string
      format: date
      description: A date in the YYYY-MM-DD format
      example: '2019-02-01'
    FloatWithCommasString:
      type: string
      pattern: ^\d{1,3}(,?\d{3})*(\.\d+)?$
      description: A float represented as a string, with optional comma delimiters
    ResponseNOTOK:
      type: object
      properties:
        status:
          type: string
          enum:
          - '0'
        message:
          type: string
          pattern: ^NOTOK(-.*)?$
          examples:
          - NOTOK
          - NOTOK-Missing/Invalid API Key, rate limit of 1/5sec applied
        result:
          type: string
      required:
      - status
      - message
      - result
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: query
      name: apikey
externalDocs:
  url: https://docs.basescan.org/
